### ISSUE TITLE
python bond.py  --> Permission denied: '/mnt/data'

### ISSUE THREAD

**Issue by drandreaskrueger** [energywebfoundation/bond#8]
```
git clone https://github.com/energywebfoundation/bond.git energywebfoundation_bond
cd energywebfoundation_bond/bond
source ../../../../envs/EWF-venv/bin/activate
python bond.py 
```

-->

```
python bond.py 

Traceback (most recent call last):
  File "bond.py", line 1, in <module>
    import core.helper as core
  File ".../energywebfoundation_bond/bond/core/helper.py", line 22, in <module>
    os.makedirs(PERSISTENCE)
  File ".../EWF-venv/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File ".../EWF-venv/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)

PermissionError: [Errno 13] Permission denied: '/mnt/data'

```

? how can I [try out](https://github.com/energywebfoundation/bond#running-on-local-environment) Bond? (not "Deploying on hardware", but "Running on local environment")

**Comment by drandreaskrueger** [comment]
same error with

```
python dyn_load_mods.py 
```
and

```
python simulator.py
```

**Comment by cerealkill** [comment]
Just change PERSISTENCE path in helper.py.
